name: Cleanup Packages
on:
  schedule:
    - cron: '15 8 * * *'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v5
        with:
          package-name: pydantic-jsonlogic
          package-type: 'docker'
          min-versions-to-keep: 2
